wordpress:
  service:
    type: ClusterIP
    externalTrafficPolicy: Local

  ingress:
    enabled: true
    pathType: Prefix
    apiVersion: "networking.k8s.io/v1"
    hostname: discourse-dev.127.0.0.1.nip.io
    path: '/'
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls: true
    selfSigned: true
