apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wp-subchart
spec:
  destination:
    namespace: wp-subchart-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-charts/wordpress-subchart/ 
    repoURL: https://github.com/ctmnz/poc-applications/
    targetRevision: main
  sync:
    comparedTo:
      destination:
        namespace: wp-subchart-ns
        server: https://kubernetes.default.svc
      source:
        path: helm-charts/wordpress-subchart/
        repoURL: https://github.com/ctmnz/poc-applications/
        targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfheal: true
    syncOptions:
    - CreateNamespace=true
