---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
  labels:
    app: simpleapp-label
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff-label
  template:
    metadata:
      labels:
        app: bff-label
    spec:
      containers:
      - name: bff
        image: 000922654503.dkr.ecr.eu-west-2.amazonaws.com/healthforcego-bff-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
