wordpress:
  service:
    type: ClusterIP
    ports:
      http: 80
      https: 443
    httpsTargetPort: https
    sessionAffinity: None
    sessionAffinityConfig: {}
    externalTrafficPolicy: Local
    #loadBalancerIP: "127.0.0.1"
    annotations: {}
    extraPorts: []

  mariadb:
    enabled: true
    architecture: standalone
    auth:
      rootPassword: ""
      username: wp-user
      password: ""
    primary:
      persistence:
        enabled: true
        storageClass: ""
        accessModes:
          - ReadWriteOnce
        size: 8Gi

  ingress:
    enabled: true
    pathType: Prefix
    apiVersion: "networking.k8s.io/v1"
    hostname: wordpress.127.0.0.1.nip.io
    path: '/'
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls: true
    selfSigned: true
  memcached:
    enabled: true
    auth:
      enabled: false
      username: ""
      password: ""
    service:
      port: 11211