mariadb:
  enabled: true
  architecture: standalone
  auth:
    rootPassword: ""
    database: wp_daniel
    username: wp-user
    password: ""
  primary:
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 8Gi
