airflow:
  service:
    type: ClusterIP
    externalTrafficPolicy: Local

  redis:
    enabled: true

  postgresql:
    enalbed: true
  
  ingress:
    enabled: true
    pathType: Prefix
    apiVersion: "networking.k8s.io/v1"
    hostname: airflow-dev.127.0.0.1.nip.io
    path: '/'
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls: true
    selfSigned: true
  git:
    dags:
      enabled: true
      repositories:
        - repository: "https://github.com/ctmnz/dag-experiments.git"
          branch: "main"
          name: "dag-experiments-name"
          path: "/"

  web: &requirements-volume-config
    extraVolumeMounts: 
      - name: requirements
        mountPath: /bitnami/python/requirements.txt
        subPath: requirements.txt
    extraVolumes:
      - name: requirements
        configMap:
          name: airflow-requirements
  scheduler: *requirements-volume-config
  worker: *requirements-volume-config

  extraDeploy:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: airflow-requirements
      data:
        requirements.txt: |
          apache-airflow-providers-google

