---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kuernetes.io/name: development
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daniel-deployment
  labels:
    app: daniel-app-label
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daniel-app-label
  template:
    metadata:
      labels:
        app: daniel-app-label
    spec:
      containers:
      - name: daniel
        image: ctmnz/simpleapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: daniel-service
  namespace: development
spec:
  selector:
    app: daniel-app-label
  ports:
    - port: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: daniel-app-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      #    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: simpleapp.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: daniel-service
            port:
              number: 5000
