---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daniel-deployment
  labels:
    app: daniel-app-label
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daniel-app-label
  template:
    metadata:
      labels:
        app: daniel-app-label
    spec:
      containers:
      - name: daniel
        image: ctmnz/simpleapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
