apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wp-subchart
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: wp-subchart-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-charts/wordpress-subchart/ 
    repoURL: https://github.com/ctmnz/poc-applications/
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
